kube-prometheus-stack:
  ## Create default rules for monitoring the cluster
  ## Disable rules for unreachable components
  ##
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeScheduler: false

  ## Disable component scraping for the kube controller manager, etcd, and kube-scheduler
  ## These components are not reachable on EKS
  ##
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false

  prometheus:
    prometheusSpec:
      ## Prometheus StorageSpec for persistent data on AWS EBS
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/storage.md
      ##
      storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

      # scrape flink jobs
      additionalScrapeConfigs:
      - job_name: flink-jobs
        scrape_interval: 5s
        metrics_path: /metrics
        scheme: http
        static_configs:
        - targets:
            - localhost:9249
            - localhost:9250
      #   kubernetes_sd_configs:
      #   - role: pod
      #     namespaces:
      #       names:
      #       - flink-operator            
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_pod_container_name]
      #     regex: ^(flink-kubernetes-operator|flink-main-container|)$
      #     action: keep
      #     target_label: pod_container_name
      #   - source_labels: [__meta_kubernetes_pod_controller_name]
      #     regex: .*
      #     action: keep
      #     target_label: pod_controller_name
      #   - source_labels: [__meta_kubernetes_pod_ip]
      #     regex: .* 
      #     target_label: pod_ip
      #   - source_labels: [__address__]
      #     action: replace
      #     regex: ([^:]+):.*
      #     replacement: $1:9249
      #     target_label: __address__
      # - job_name: flink-jobs-9250
      #   scrape_interval: 5s
      #   metrics_path: /metrics
      #   scheme: http
      #   static_configs:
      #   - targets:
      #       - localhost:9249
      #       - localhost:9250
      #   kubernetes_sd_configs:
      #   - role: pod
      #     namespaces:
      #       names:
      #       - flink-operator            
      #   relabel_configs:
      #   - source_labels: [__meta_kubernetes_pod_container_name]
      #     regex: ^(flink-kubernetes-operator|flink-main-container|)$
      #     action: keep
      #     target_label: pod_container_name
      #   - source_labels: [__meta_kubernetes_pod_controller_name]
      #     regex: .*
      #     action: keep
      #     target_label: pod_controller_name
      #   - source_labels: [__meta_kubernetes_pod_ip]
      #     regex: .* 
      #     target_label: pod_ip
      #   - source_labels: [__address__]
      #     action: replace
      #     regex: ([^:]+):.*
      #     replacement: $1:9250
      #     target_label: __address__
          
  prometheusOperator:
    admissionWebhooks:
      failurePolicy: Ignore

  ## additional configuration options available here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml