{{- if and (.Values.calico) (.Values.calico.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/calico
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        calico:
        {{- toYaml .Values.calico | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
