{{- if and (.Values.consul) (.Values.consul.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/consul
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        consul:
        {{- toYaml .Values.consul | nindent 10 }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: consul
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
