{{- if and (.Values.kubeflowPipeline) (.Values.kubeflowPipeline.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipeline
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/kubeflow-pipeline
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        kubeflow-pipeline:
        {{- toYaml .Values.kubeflowPipeline | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow-pipeline
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
