{{- if and (.Values.prometheusNodeExporter) (.Values.prometheusNodeExporter.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/prometheus-node-exporter
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        prometheus-node-exporter:
        {{- toYaml .Values.promtheusNodeExporter | nindent 10 }}
      parameters:
      - name: prometheus-node-exporter.serviceAccount.name
        value: {{ .Values.promtheusNodeExporter.serviceAccountName }}
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: prometheus-node-exporter
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
