{{- if and (.Values.timescaleDbSingle) (.Values.timescaleDbSingle.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timescaledb-single
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: add-ons/timescaledb-single
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        timescaleDbSingle:
        {{- toYaml .Values.timescaleDbSingle | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: timescale
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
