apiVersion: v2
name: aws-load-balancer-controller
description: A Helm chart for installing AWS Load balacer controller
type: application

# The chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# Version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0"

dependencies:
- name: aws-load-balancer-controller
  version: 1.3.2
  repository: https://aws.github.io/eks-charts