cluster-autoscaler:
  extraArgs:
    aws-use-static-instance-list: true

  rbac:
    serviceAccount:
      create: false

  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
