{{- if .Values.agones.enable -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-cloudwatch-metrics 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io    
spec:
  project: default
  source:
    repoURL: https://github.com/kcoleman731/argo-add-ons
    path: add-ons/aws-cloudwatch-metrics 
    targetRevision: HEAD
    helm: 
      parameters:
      - name: aws-cloudwatch-metrics.clusterName
        value: {{ .Values.clusterName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: amazon-cloudwatch
  syncPolicy:
    automated:
      prune: true    
    syncOptions:
    - CreateNamespace=true 
    retry:
      limit: 1
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m  
{{- end -}}