cilium:
  cni:
    chainingMode: aws-cni
  enableIPv4Masquerade: false
  tunnel: disabled
  operator:
    rollOutPods: true
  relay:
    rollOutPods: true
  hubble:
    rollOutPods: true
    ui:
      enabled: true
    relay:
      enabled: true
